export const locations = [
  { name: "201 High Street Willoughby, NSW, 2068" },
  { name: "119-121 Johnston Street Annandale, NSW, 2038" },
  { name: "14a Hannah St Beecroft, NSW, 2119" },
  { name: "144-146 Curlewis Street Bondi Beach, NSW, 2026" },
  { name: "194-196 Coogee Bay Road Coogee, NSW, 2034" },
  { name: "10 Howard Avenue Dee Why, NSW, 2099" },
  { name: "172 Lyons Road Drummoyne, NSW, 2047" },
  { name: "Forestway Shopping Centre Frenchs Forest, NSW, 2086" },
  { name: "27 Burns Bay Road Lane Cove, NSW, 2066" },
  { name: "Shop RT1, Wicks Place 186 Victoria Road Marrickville, NSW, 2204" },
  { name: "4/1785 Pittwater Road Mona Vale, NSW, 2103" },
  { name: "Shop 3 / 4-8 Waters Lane Neutral Bay, NSW, 2089" },
  { name: "Studio Drive Eastgardens, NSW, 2036" },
  { name: "55C Frenchmans Road Randwick, NSW, 2031" },
  { name: "2 / 779 New South Head Road Rose Bay, NSW, 2029" },
  { name: "213A Mona Vale Road St Ives, NSW, 2075" },
  { name: "16 Railway Avenue Wahroonga, NSW, 2076" },
  { name: "134 Queen Street Woollahra, NSW, 2025" },
];

export const categories = [
  {
    name: "Extra Large Seasoned Chicken",
    category: "Chicken",
    size: "Whole (cut into 8 pieces)",
    price: "$22.90",
    dietary: ["GF"],
  },
  {
    name: "Portuguese Chicken",
    category: "Chicken",
    size: "Whole (cut into 8 pieces)",
    price: "$22.90",
    dietary: ["GF"],
  },

  {
    name: "Greek Salad",
    category: "Salad",
    size: "Regular (serves 10–15)",
    price: "$75.00",
    dietary: ["VG", "GF"],
  },
  {
    name: "Caesar Salad",
    category: "Salad",
    size: "Regular (serves 10–15)",
    price: "$75.00",
    dietary: ["GF"],
  },
  {
    name: "Garden Salad",
    category: "Salad",
    size: "Regular (serves 10–15)",
    price: "$75.00",
    dietary: ["VG", "GF"],
  },
  {
    name: "Coleslaw",
    category: "Salad",
    size: "Regular (serves 10–15)",
    price: "$75.00",
    dietary: ["VG"],
  },
  {
    name: "Potato Salad",
    category: "Salad",
    size: "Regular (serves 10–15)",
    price: "$75.00",
    dietary: ["VG"],
  },

  {
    name: "Hot Chips",
    category: "Sides",
    size: "Regular (serves 10)",
    price: "$45.00",
    dietary: ["GF"],
  },
  {
    name: "Wedges",
    category: "Sides",
    size: "Regular (serves 10)",
    price: "$50.00",
    dietary: ["GF"],
  },
  {
    name: "Sweet Potato Wedges",
    category: "Sides",
    size: "Regular (serves 10)",
    price: "$60.00",
    dietary: ["GF"],
  },
  {
    name: "Mac & Cheese",
    category: "Sides",
    size: "Regular (serves 10–15)",
    price: "$75.00",
    dietary: ["GF"],
  },
  {
    name: "Rigatoni Bolognese",
    category: "Sides",
    size: "Regular (serves 10–15)",
    price: "$75.00",
    dietary: ["GF"],
  },
  {
    name: "Cauliflower Cheese",
    category: "Sides",
    size: "Regular (serves 10–15)",
    price: "$75.00",
    dietary: ["GF"],
  },
  {
    name: "Steamed Vegetables",
    category: "Sides",
    size: "Regular (serves 10–15)",
    price: "$75.00",
    dietary: ["VG", "GF"],
  },
  {
    name: "Family Vegetable Roast",
    category: "Sides",
    size: "Regular (serves 10–15)",
    price: "$75.00",
    dietary: ["VG", "GF"],
  },
  {
    name: "Honey 'N Mustard Baked Veg",
    category: "Sides",
    size: "Regular (serves 10–15)",
    price: "$75.00",
    dietary: ["VG", "GF"],
  },
  {
    name: "Lentil Curry",
    category: "Sides",
    size: "Regular (serves ~12)",
    price: "$75.00",
    dietary: ["VG", "GF"],
  },
  {
    name: "Chicken Nasi Goreng",
    category: "Sides",
    size: "Regular (serves 10–15)",
    price: "$75.00",
    dietary: ["GF"],
  },
  {
    name: "Chicken Pad Thai",
    category: "Sides",
    size: "Regular (serves 10–15)",
    price: "$75.00",
    dietary: ["GF"],
  },
  {
    name: "Fried Rice",
    category: "Sides",
    size: "Regular (serves 10–15)",
    price: "$75.00",
    dietary: ["GF"],
  },
  {
    name: "Baked Pumpkin",
    category: "Sides",
    size: "Regular (serves 10–15)",
    price: "$75.00",
    dietary: ["VG", "GF"],
  },
  {
    name: "Chicken Schnitzel",
    category: "Sides",
    size: "Per piece (min 10)",
    price: "$8.90",
    dietary: ["CN"],
  },

  {
    name: "Chooka's Pack",
    category: "Sharing Boxes",
    size: "Regular (serves 10)",
    price: "$125.00",
    dietary: ["GF"],
  },
  {
    name: "Chooka's Pack",
    category: "Sharing Boxes",
    size: "Large (serves 15)",
    price: "$165.00",
    dietary: ["GF"],
  },
  {
    name: "Chooka's Pack",
    category: "Sharing Boxes",
    size: "Extra Large (serves 20)",
    price: "$220.00",
    dietary: ["GF"],
  },
  {
    name: "Charlie's Angels",
    category: "Sharing Boxes",
    size: "Regular (serves 10)",
    price: "$125.00",
    dietary: ["GF"],
  },
  {
    name: "Charlie's Angels",
    category: "Sharing Boxes",
    size: "Large (serves 15)",
    price: "$165.00",
    dietary: ["GF"],
  },
  {
    name: "Charlie's Angels",
    category: "Sharing Boxes",
    size: "Extra Large (serves 20)",
    price: "$220.00",
    dietary: ["GF"],
  },

  {
    name: "Rice Paper Roll Box",
    category: "Finger Food",
    size: "Box of 20 pieces",
    price: "$100.00",
    dietary: ["VG", "GF"],
  },
  {
    name: "Comeback Chicken Skewers",
    category: "Finger Food",
    size: "Box of 20 pieces",
    price: "$85.00",
    dietary: ["GF"],
  },
  {
    name: "Beef and Guinness Empanadas",
    category: "Finger Food",
    size: "Box of 20 pieces",
    price: "$100.00",
    dietary: ["CN"],
  },

  {
    name: "Soft Drink Bottle",
    category: "Drinks",
    size: "600ml",
    price: "$4.75 (min 10 bottles)",
    dietary: [],
  },
  {
    name: "Soft Drink Bottle",
    category: "Drinks",
    size: "1.25L",
    price: "$6.00",
    dietary: [],
  },
];
